### PR TITLE
DEV/MNT: migrate to latest standards with pyproject.toml [LCLSPC-603]

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Upgrading by way of https://github.com/pcdshub/pcds-python-migration-tools
* pcdsdaq has been migrated to use setuptools-scm, replacing versioneer, as its version-string management tool of choice.
* pcdsdaq has been migrated to use the modern ``pyproject.toml``, replacing ``setup.py`` and related files.
* Older language features and syntax found in the repository have been updated to Python 3.9+ standards by way of ``pyupgrade``.
* Sphinx 6.0 is now supported for documentation building. ``docs-versions-menu`` replaces ``doctr-versions-menu`` and ``doctr`` usage for documentation deployment on GitHub Actions.  The deployment key is now no longer required.
* `pyupgrade` was used to update annotations, though there might not have been many here
* `pycln` was used to clean up imports

## Motivation and Context
* Migrating because we want to migrate our projects from Travis CI for one
* Second migration attempt after nudging #108 

## How Has This Been Tested?
* GitHub Actions

## Where Has This Been Documented?
This PR and Jira [LCLSPC-603](https://jira.slac.stanford.edu/browse/LCLSPC-603)

### CODE REVIEW

**Comment by klauer** [comment]
A few issues:
* psdaq-control-minimal isn't/won't be on pypi any time soon, so pip builds will fail
* There's a reliance on type hints where we run into a similar issue as in atef: `int | float | None` is fine with `from __future__ import annotations` but is problematic when we try to evaluate those type hints in Python < 3.10.
    * https://github.com/klauer/pcdsdaq/blob/47abeb2703211b2d7d10d84713a4410b2ad2cf71/pcdsdaq/daq/interface.py#L229-L268
* There's one failing test in 3.10/conda: https://github.com/pcdshub/pcdsdaq/actions/runs/4367132731/jobs/7638055269
* 3.11/conda lightpath strikes again

**Comment by klauer** [comment]
I reverted the type hint-related issue. I'm not sure if the currently-failing test _should be_ failing since Travis CI just didn't run on this repo previously. I'll ask for Zach to review and see what he thinks.

**Comment by ZLLentz** [comment]
Based on my docstrings and comments, the failing test is an actual failure (barring test setup error possibilities, etc.)
I can make an issue to revisit:
- The failing test
- Make psdaq an optional dependency and skip tests that need it when missing

**Review by ZLLentz — APPROVED** [review]
This looks good to me

**Pull request merged**
