### PR TITLE
REL: release notes v2.4.4

### PR DESCRIPTION
**Pull request by tangkong**
## Description
Release notes for v2.4.4

## Motivation and Context
tiny tag (tt)

## How Has This Been Tested?
N/A

## Where Has This Been Documented?
you're lookin at it

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
Is there some new bluesky incompatibility here, similar to nabs?

**Review by ZLLentz — DISMISSED** [review]

**Comment by tangkong** [comment]
Sigh, yes.  numpy.product was deprecated in 1.25, not even 2.0

**Comment by ZLLentz** [comment]
Fixed upstream in https://github.com/bluesky/bluesky/pull/1672

**Comment by tangkong** [comment]
Ah they still haven't tagged any of the 1.13 releases as latest ..

**Review by ZLLentz — APPROVED** [review]
I agree with your decisions here

**Pull request merged**
